# Generated by Django 2.0.13 on 2019-05-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThiefLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user_id',
            new_name='status',
        ),
        migrations.AddField(
            model_name='person',
            name='national_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
