# Generated by Django 2.0.13 on 2019-05-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190514_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThiefLocation',
            new_name='Location',
        ),
    ]
