# Generated by Django 2.0.13 on 2019-05-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190515_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='ThiefLocation',
        ),
    ]
